### ISSUE TITLE
'No buffer space available' error while testing

### ISSUE THREAD

**Issue by sedenmutaf1** [Ozyegin-Planetary-Robotics-Laboratory/tmotorcan-cpp#1]
When the AK60Manager is instantiated, it gives continuous "Error while writing to socket: No buffer space available" error.There is no problem with writing the frame, motor does work.

**Comment by Toprak-Efe** [comment]
Increasing the txqueue size solves the problem as it allows for leniency against the thread sending the messages.
Simply do `sudo ip link set can0 txqueuelen 1000` before setting the interface up.
